// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL1L2SCsAYwQ4aBZXIeBxnWXH97H6xNFk',
    appId: '1:906889692024:web:1ddc32e72f95ef27a67e8d',
    messagingSenderId: '906889692024',
    projectId: 'lab3-mis-ff35b',
    authDomain: 'lab3-mis-ff35b.firebaseapp.com',
    storageBucket: 'lab3-mis-ff35b.firebasestorage.app',
    measurementId: 'G-D0GJCBG77X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9ZDveuKIyZRQQIIhk1ntbWYGgnifMu5s',
    appId: '1:906889692024:android:ba2e2b9b5ac97a7fa67e8d',
    messagingSenderId: '906889692024',
    projectId: 'lab3-mis-ff35b',
    storageBucket: 'lab3-mis-ff35b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmUCsxcvZA2JaXDqgJrqfI1wkBT0m2OT8',
    appId: '1:906889692024:ios:74eb45f80e911082a67e8d',
    messagingSenderId: '906889692024',
    projectId: 'lab3-mis-ff35b',
    storageBucket: 'lab3-mis-ff35b.firebasestorage.app',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmUCsxcvZA2JaXDqgJrqfI1wkBT0m2OT8',
    appId: '1:906889692024:ios:74eb45f80e911082a67e8d',
    messagingSenderId: '906889692024',
    projectId: 'lab3-mis-ff35b',
    storageBucket: 'lab3-mis-ff35b.firebasestorage.app',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL1L2SCsAYwQ4aBZXIeBxnWXH97H6xNFk',
    appId: '1:906889692024:web:2328e397086d4b2da67e8d',
    messagingSenderId: '906889692024',
    projectId: 'lab3-mis-ff35b',
    authDomain: 'lab3-mis-ff35b.firebaseapp.com',
    storageBucket: 'lab3-mis-ff35b.firebasestorage.app',
    measurementId: 'G-D75VGZKZ0J',
  );
}
